### ISSUE TITLE
Please change Cutes keywords detection to whole word detection and not substring.

### ISSUE THREAD

**Issue by Raffael7777** [powercord-community/cutecord#10]
I cannot be the only user aggravated by this issue. Many of my friends call me "raff", short for Raffael, my discord name. I would like to receive notifications when "raff" or "raffael" are said, so I added both as Cutes keywords. But I do not want to receive an alert every time someone says "traffic", "giraffe", or "straffing", or for every single raffle every server is holding, which is the result of the current substring keyword detection. The settings for Cutecord do not allow for spaces to be on either side of keywords.

**Comment by katlyn** [comment]
v3.2.0 adds this, as well as an advanced setting option to let the user decide which detection method to use. It defaults to word.

![image](https://user-images.githubusercontent.com/17418611/110069161-7afb6800-7d34-11eb-8fee-87cebc887153.png)
