### ISSUE TITLE
Case sensitive keywords

### ISSUE THREAD

**Issue by fawni** [powercord-community/cutecord#11]
the keywords are case sensitive so if i set "lol" as a cute keyword i won't get notifications for "LOL" or "Lol" or any other variations, i dont know if that's intentional or not but if it is, could you please add an option to disable it?

**Comment by katlyn** [comment]
This has been implemented and a new option has been added to the advanced settings menu. It defaults to case insensitive detection.
![image](https://user-images.githubusercontent.com/17418611/113638516-41b85f80-9634-11eb-9c22-ed6044d0646b.png)
