### ISSUE TITLE
No notification if uppercase letters are in cuties keywords list. 

### ISSUE THREAD

**Issue by MMOOBB** [powercord-community/cutecord#14]
Say you want to notified by the word "Apple". If it's in the word list as the characters "apple", it works perfectly fine, no problems there. However, if you add it in as "Apple" (capital A), it no longer works, even with case insensitivity. 

Not sure if this was overlooked or ignored, but I was confused at first, thinking the plugin wasn't working when I did the latter case. 

works with notifs, no matter the case 
![image](https://user-images.githubusercontent.com/33990719/114133688-0768ef80-98cc-11eb-83b0-e49b9a2ae6de.png) 
no longer works
![image](https://user-images.githubusercontent.com/33990719/114133759-2b2c3580-98cc-11eb-9a03-de9d30d95b19.png)

**Comment by dapal-003** [comment]
I've fixed this issue in PR https://github.com/powercord-community/cutecord/pull/16
