### ISSUE TITLE
created a lockfile as package-lock.json. You should commit this file.

### ISSUE THREAD

**Issue by CinnamonOwl** [powercord-community/cutecord#18]
This may be a stupid issue because I'm a complete noob, but I've run into this notice while trying to install cutecord and have not idea how to fix it even after googling. What did I miss?

**Comment by katlyn** [comment]
I'm not sure where you'd be getting this error, that should only come up when you run `npm install` which isn't required for this plugin. I know this is a late response, but are you sure you're following the correct install procedure?
