### ISSUE TITLE
Meanie feature fails to block notifications and messages from being received.

### ISSUE THREAD

**Issue by Triantafyllo** [powercord-community/cutecord#21]
**Issue**
You can still receive and see DMs from people marked as "Meanies".

**Expected behaviour**
The notification and message are never received until the client is reloaded.

**Actual behaviour**
The notification and message are received, even if there was a reload after adding a person as meanie.

**Comment by katlyn** [comment]
Cutecord only deals with notifications directly (as in the sound and system toasts). It will not get rid of unread indicators, unread dms, or notification dots from pings and it does not prevent messages from being received. What you're describing sounds like intended functionality.
