### ISSUE TITLE
[Feature Request] Add Cute Groups

### ISSUE THREAD

**Issue by xPolar** [powercord-community/cutecord#22]
We're able to add cute users but it would also be nice to be able to add cute group DMs.

**Comment by katlyn** [comment]
You should be able to add group DMs as cute by putting their channel IDs in the cute channels sections. If you've tried this and it hasn't worked then I'll mark this as a bug.

**Comment by xPolar** [comment]
That worked, was wishing there was a button to mark channels and group DMs as a cute / mean channel though. Just a small little quality of life thing.
