### ISSUE TITLE
An option to make online status act like dnd

### ISSUE THREAD

**Issue by AugustusUKR** [powercord-community/cutecord#23]
I think this would be useful because I enjoy only getting notifications from _cutes_ but I would like people to know when I'm away/idle

**Comment by katlyn** [comment]
This will be addressed with #32

**Comment by katlyn** [comment]
Now that #32 has been merged, this is possible. See the [changelog](https://github.com/powercord-community/cutecord/blob/v4/changelog.md#status-overrides).
