### ISSUE TITLE
Cutecord doesn't work?

### ISSUE THREAD

**Issue by Knobibrot** [powercord-community/cutecord#24]
I'm in a server that I muted but I want to receive notifs for one particular user. So I installed cutecord and added them as cutie. But I still don't get a notification when they post something. Also, if I read the update log correctly, the usernames of cuties should have a flower next to it, but there is no flower. When I right-click the user, there is the "Remove cute" option, so I think they are added correctly.

Is there anything else I could have done wrong?

**Comment by katlyn** [comment]
As mentioned in the [v3.1.0 changelog](https://github.com/powercord-community/cutecord#v310), cute badges have been removed. The [How cutecord works](https://github.com/powercord-community/cutecord#how-cutecord-works) section of the readme also shows that muted guilds and channels are checked before cute users are - if you've muted a guild, you won't get any notifications from it, even if a cute user triggers the notification.

**Comment by Knobibrot** [comment]
Oh, that's not how I understood the guide. In thought it meant it checks for muted channels or servers in order to override the mute. In that case I'm sorry, there is no issue; cutecord just doesn't do what I need.
