### ISSUE TITLE
Notifications overriding DND status regardless of override setting

### ISSUE THREAD

**Issue by F4therThyme** [powercord-community/cutecord#26]
Whether added to the cutie list or not notification sounds still go through as if DND is not active.

**Comment by katlyn** [comment]
Can you show what you have your settings configured as? there's a setting that makes DND act like any other status, and that would be the expected behavior if you had it enabled.

**Comment by F4therThyme** [comment]
https://i.imgur.com/yZE40qs.png

**Comment by katlyn** [comment]
I'll take a look into this later in the next few days.
