### ISSUE TITLE
Weird bug

### ISSUE THREAD

**Issue by LandenStephenss** [powercord-community/cutecord#3]
![image](https://user-images.githubusercontent.com/36753435/74671237-56a40c00-5170-11ea-9584-033ac3f9ab8f.png)

**Comment by katlyn** [comment]
If anyone is able to reproduce this I will take another look, but so far I've not come across it at all in my own testing.

**Comment by LandenStephenss** [comment]
I think that it might be something related to my pc or just discord being funky in general. Sometimes ill get errors like that about random modules from random plugins. I think it might just be something to do with discord/powercord's loading.

Although i'm not 100% sure what it might be since this issue was posted like a year ago
