### ISSUE TITLE
Cute users notify on all messages when in DND

### ISSUE THREAD

**Issue by ghost** [powercord-community/cutecord#9]
I've added some friends of mine to the cuties list, so I can actually see their DMs while I'm on DND, but I've noticed I get notified of the messages they send in mutal servers, too. Is there a way to disable this?

![2021-02-16 11_11_03-Window](https://user-images.githubusercontent.com/78015856/108041845-c41a9f00-7047-11eb-81d4-7da767c1277d.png)

**Comment by katlyn** [comment]
This is fixed with #32.
